
# FAZENDO UMA AMOSTRAGEM PARA DESENVOLVER O SCRIPT MAI RÁÍDO
set.seed(42) # Para reprodutibilidade

SAMPLE_BASE <- BASE[sample(nrow(BASE), 100, replace = TRUE), ]
SAMPLE_BASE

# REMOVENDO A BASE-COMPLETA DA MEMORIA PARA NÃO AFETAR O COMPUTADOR
rm(BASE)